name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        runtime: [win-x64, linux-x64, linux-arm64, osx-x64, osx-arm64]

    runs-on: ${{ matrix.runtime == 'win-x64' && 'windows-latest' || 'ubuntu-latest' }}

    env:
      Solution_Name: your-solution-name.sln  # Replace with your solution name
      Output_Directory: publish-output/${{ matrix.runtime }}  # Output directory based on runtime

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Skipping .NET SDK setup since it is already installed

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Publish self-contained single-file executable
      run: |
        dotnet publish $env:Solution_Name \
          --configuration ${{ matrix.configuration }} \
          --output $env:Output_Directory \
          -p:PublishSingleFile=true \
          -p:SelfContained=true \
          -p:PublishTrimmed=true \
          -r ${{ matrix.runtime }}
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Published Executable - ${{ matrix.runtime }}
        path: ${{ env.Output_Directory }}
