name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        runtime: [win-x64, linux-x64, linux-arm64, osx-x64, osx-arm64]

    runs-on: ${{ matrix.runtime == 'win-x64' && 'windows-latest' || 'ubuntu-latest' }}

    env:
      Output_Directory: publish-output/${{ matrix.runtime }}  # Output directory based on runtime

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Skipping .NET SDK setup since it is already installed

    - name: Restore dependencies
      run: dotnet restore lain.sln  # Directly reference the solution file

    - name: Publish self-contained single-file executable
      run: |
        dotnet publish lain.sln --configuration Release --output $env:Output_Directory -p:PublishSingleFile=true -p:SelfContained=true -p:PublishTrimmed=true -r ${{ matrix.runtime }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Published Executables
        path: ${{ env.Output_Directory }}
